### ISSUE TITLE
KupiaSec - Incorrect overlap check in swapping validators

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-rio-network-core-protocol-judging#292]
KupiaSec

high

# Incorrect overlap check in swapping validators

## Summary
Index calculation is not correct in checking overlap thus swapping validators revert.

## Vulnerability Detail
In `swapValidatorDetails` function in `ValidatorDetails` contract, it checks if two segments overlap to prevent swapping overlapping validators:
```Solidity
// forgefmt: disable-next-item
// Ensure no overlap in indexes
if ((startIndex1 < startIndex2 && startIndex1 + keysCount >= startIndex2) || (startIndex2 < startIndex1 && startIndex2 + keysCount >= startIndex1)) {
    revert INDEXES_OVERLAP();
}
```

The issue here is that `startIndex1 + keysCount >= startIndex2` comparison is incorrect, it has to be `>` instead of `>=`.
Because, the last index of first segment is `startIndex1 + keysCount - 1`, so when two segments overlap, it satisfies `startIndex1 + keysCount - 1 >= startIndex2`, thus `startIndex1 + keysCount > startIndex2`.

For example, assume `startIndex1` is 3, `keysCount is 3`, `startIndex2` is 6.
First segment includes indices 3, 4, 5, and the second segment includes indices 6, 7, 8.
Since these two segments do not overlap, it should be able to swap, but from above check, it reverts.

## Impact
Validator swapping feature reverts.

## Code Snippet
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/utils/ValidatorDetails.sol#L129-L131

## Tool used
Manual Review

## Recommendation
Update check as follows:
```Solidity
if ((startIndex1 < startIndex2 && startIndex1 + keysCount > startIndex2) || (startIndex2 < startIndex1 && startIndex2 + keysCount > startIndex1)) {
    revert INDEXES_OVERLAP();
}
```

**Comment by KupiaSecAdmin** [comment]
Escalate

@nevillehuang @solimander - This issue describes a different case from #183, and the issue can't be resolved by splitting.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> @nevillehuang @solimander - This issue describes a different case from #183, and the issue can't be resolved by splitting.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
Disagree with escalation, I believe there is no differences in underlying root cause and should remain duplicated to #183, it reverts at the exact same line of code, so please provide a PoC if you think otherwise @KupiaSecAdmin

**Comment by KupiaSecAdmin** [comment]
Detailed example is attached to Vulnerability Details. Basically, adjacent segments can not be swapped.

**Comment by KupiaSecAdmin** [comment]
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/280

This issue describes the same as well.

**Comment by Czar102** [comment]
@nevillehuang can you explain what is the single root cause in a few words so that both issues will fall under this description?

**Comment by nevillehuang** [comment]
@Czar102 I agree with @KupiaSecAdmin this is a separate issue from #183 based on discussions there, but I believe is low severity given there is a workaround with no loss of funds and the unlikely scenario that this would occur based on intended number of validators per operator as mentioned by sponsor [comments here](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/183#issuecomment-2041503201)

**Comment by Czar102** [comment]
In that case, planning to reject the escalation and leave it a Low severity issue.

**Comment by KupiaSecAdmin** [comment]
@nevillehuang - I saw your question in the #183 asking if an operator contains less than 3 validators or not. Would you please let me know how less than 3 validators mark this issue Low/Invalid? The issue happens for any adjacent segment that wanna be swapped each other. I think it would deserve Med severity.

**Comment by nevillehuang** [comment]
@KupiaSecAdmin I was responding to hash example. There is a workaround without fund loss that allows admin to perform this action without any loss of funds as mentioned [here](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/183#issuecomment-2032079945), hence I believe it to be low severity since no core contract functionality is broken.

**Comment by KupiaSecAdmin** [comment]
> > @10xhash do you agree with Medium?
> > I'm planning to make this issue valid and accept the escalation.
> 
> I think its borderline med / low
> 
> @KupiaSecAdmin I agree that this report fails to correctly identify the vulnerability. This report points to a scenario which includes the same vulnerability (when the count is equal to fromIndex and exited is 0, it will be an adjacent index case) fromIndex = 3, validatorCount = 3 to be exited [3,4,5] to be shifted [0,1,2] no index overlap
> 
> But the mentioned issue (`when validators.exited is 0 and validatorCount is greater than or equal to fromIndex`) points to reverts occurring in a different scenario, which is intended by the team (reverts when indexes overlap) fromIndex = 3, validatorCount = 4 to be exited [3,4,5.6] to be shifted [0,1,2,3] index 3 overlaps

@nevillehuang - I assume you were referring to the second one right? If so, yes, the second example describes the parent issue, on the other hand, the first example by Hash represents the issue that Hash and I reported.

**Comment by KupiaSecAdmin** [comment]
I think for this issue, there's no workaround to avoid the revert for adjacent segments to be swapped.

**Comment by nevillehuang** [comment]
@KupiaSecAdmin I believe the sponsors [comment here](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/183#issuecomment-2028767691) is referring to your scenario, not #183. I agree #183 is invalid.

**Comment by KupiaSecAdmin** [comment]
@nevillehuang - based on the discussion between Hash and the protocol team, there can be workaround to avoid revert issue, which is to split validators into 1 and (N-1) that makes two segments not adjacent. However in this case, the one exited validator will remain as active validator throughout Rio protocol because it can't be removed because of this issue.

As long as the exited validator remains as active, there happens other issues throughout the protocol. One main example would be allocating ETH between validators.

```Solidity
uint256 activeDeposits = validators.deposited - validators.exited;
```

In `allocateETHDeposits` function, it defines active number of validators via the formula above, and at the end deposits 32 ETH * activeDeposits into EigenLayer. This means 32 ETH is staked as name of exited validator which I think is a problem.
Not sure how the logic is implemented in EigenLayer, but probably it will revert when it tries to deposit ETH into exited validator. In this case, `allocateETH` function which is a part of `rebalance` reverts.

**Comment by nevillehuang** [comment]
@KupiaSecAdmin Could you confirm this impact with a PoC? If true, definitely agree with medium severity. Rebalancing reverting means loss of funds because withdrawals are bricked correct? I believe rebalancing should never revert under any circumstances

cc: @solimander

**Comment by KupiaSecAdmin** [comment]
@nevillehuang - Well, I think it depends on EigenLayer implementation. If they revert on invalid deposit, rebalance will revert. If they don't, it causes 32ETH on Rio Protocol. Also this specific impact does not come from withdrawals, it happens because the exited validator is assumed as active validator in Rio protocol because it literally can't be removed.

**Comment by nevillehuang** [comment]
@KupiaSecAdmin What implementation are you referring to and how would it cause a loss of 32 ETH? This could be high severity if it really causes that much loss.

**Comment by solimander** [comment]
@KupiaSecAdmin It would not try to deposit into an exited validator.  Instead, it would just make one less deposit than what's possible if the operator's cap is hit because there is an extra active deposit that hasn't been reported as exited yet. No loss is possible.

**Comment by KupiaSecAdmin** [comment]
@nevillehuang - Based on my research around EigenLayer and ETH PoS staking, I think rebalance function will revert, which I think might be High severity because it is not recoverable. Here's my explanation:
(First and foremost, we assume that the one exited validator at index `exited` can not be removed because of the issue reported here)


When `rebalance` function is called, it allocates deposited ETH between operators based on their availability(active = deposited - exited) and utilization rate. This means that 32ETH will be staked again into EigenLayer and into ETH PoS Consensus.

`RioLRTOperatorDelegator.sol` -> `stakeETH` function:
```Solidity
eigenPodManager.stake{value: ETH_DEPOSIT_SIZE}(publicKey, signature, depositDataRoot);
```

From Rio, it deposits (32 * active) ETH into EigenLayer.

EigenLayer's `EigenPod` contract:
```Solidity
ethPOS.deposit{value: 32 ether}(pubkey, _podWithdrawalCredentials(), signature, depositDataRoot);
```

And at the end, those ETH are deposited into Ethereum PoS deposit contract. However it will revert because the signature it passes over is incorrect for that exited validator.
Thus, the `rebalance` function will revert finally, and I think it can not be recovered once this happens.

Also @nevillehuang - Can we include Hash in this thread as well?

**Comment by KupiaSecAdmin** [comment]
> @KupiaSecAdmin It would not try to deposit into an exited validator. Instead, it would just make one less deposit than what's possible if the operator's cap is hit because there is an extra active deposit that hasn't been reported as exited yet. No loss is possible.

@solimander - I am sorry I didn't quite understand it yet. If the exited validator can't be removed from an operator which means `exited` does not increase, `activateValidators` does not decrease. Doesn't it mean the exited operator is still considered active thus next time rebalance happens, 32ETH will be deposited to the validator?

**Comment by solimander** [comment]
@KupiaSecAdmin No, "active" refers to validators that have already received a deposit. `validators.deposited` is used to determine the next validator to deposit to, not `activeDeposits` or `validators.exited`.

Failure to decrease `activeDeposits` would instead cause the operator to receive one less deposit than what their cap could potentially support because the system doesn't realize that one of the active deposits is no longer active. Does that make sense?

**Comment by KupiaSecAdmin** [comment]
@nevillehuang @solimander - After looking into the codebase and logic again, I think my assumption above was wrong. It can not have that kind of impact.

@solimander - Another point I concern about is the validator can't be removed still earn profits from Rio protocol even though it exited as long as it doesn't require withdrawals?

**Comment by solimander** [comment]
> Another point I concern about is the validator can't be removed still earn profits from Rio protocol even though it exited as long as it doesn't require withdrawals?

@KupiaSecAdmin The validator itself doesn't earn profits from the Rio protocol, so in this sense it doesn't matter if it's been reported as exited or not.

**Comment by KupiaSecAdmin** [comment]
> > Another point I concern about is the validator can't be removed still earn profits from Rio protocol even though it exited as long as it doesn't require withdrawals?
> 
> @KupiaSecAdmin The validator itself doesn't earn profits from the Rio protocol, so in this sense it doesn't matter if it's been reported as exited or not.

What about the operators that includes unremovable validator?

**Comment by solimander** [comment]
> What about the operators that includes unremovable validator?

You can still deactivate the operator or set their validator cap to 0 to disable future rewards and report the exit at any time.

**Comment by KupiaSecAdmin** [comment]
Alright, thanks for the explanation. Seems the impact might be Low.

**Comment by Czar102** [comment]
Result:
Low
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [KupiaSecAdmin](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/292/#issuecomment-2020073813): rejected
