### ISSUE TITLE
Topmark - Token Amount Value would be Lost due to Precision Loss from Token Decimal Conversion

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-rio-network-core-protocol-judging#38]
Topmark

medium

# Token Amount Value would be Lost due to Precision Loss from Token Decimal Conversion

## Summary
Token Amount Value would be Lost due to Precision Loss after _normalizeDecimals(...) function call in the RioLRTAssetRegistry.sol contract  during Decimal conversion
## Vulnerability Detail
```solidity
  function _normalizeDecimals(uint256 amount, uint8 fromDecimals, uint8 toDecimals) internal pure returns (uint256) {
        // No adjustment needed if decimals are the same.
        if (fromDecimals == toDecimals) {
            return amount;
        }
        // Scale down to match the target decimal precision.
        if (fromDecimals > toDecimals) {
   >>>         return amount / 10 ** (fromDecimals - toDecimals);
        }
        // Scale up to match the target decimal precision.
        return amount * 10 ** (toDecimals - fromDecimals);
    }
```
The function above shows how _normalizeDecimals(...) function is implemented for token decimal conversion in the RioLRTAssetRegistry.sol contract, the problem is that when Decimal is being converted from a token with higher decimal value to Token with Lower decimal Value due to the division operation as noted from the pointer from the code above, There would be precision loss and this excess value is not accounted for, it would be completely lost to the smart contract calling this conversion.
## Impact
Token Amount Value would be Lost due to Precision Loss after _normalizeDecimals(...) function call in the RioLRTAssetRegistry.sol contract 
## Code Snippet
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTAssetRegistry.sol#L374
## Tool used

Manual Review

## Recommendation
Rio Protocol should make necessary implementation to ensure this token value is not completely lost during Token Decimal conversion and to ensure the excess value can be extracted when needed by the protocol

**Comment by Topmark1** [comment]
@nevillehuang I believe this judgement is unfair to the watson's effort, this is a valid issue as the a pointer is present in the code to show where the problem is in as simple as possible way and also the description also noted that the precision lose only occurs when converting from higher decimal to lower decimal, Judge should please reconsider thank you.
The sherlock rules state that POC is only required for a non obvious vulnerability with complex vulnerability paths as quoted `non-obvious ones with complex vulnerabilities/attack paths` .
This issue is quite basic and easy to understand and spot, even the Judge understood what the issue the report was aiming at, once again, Judge should please reconsider thank you.

**Comment by Topmark1** [comment]
[Escalate]

**Comment by Topmark1** [comment]
Escalate

Reason noted above

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Reason noted above

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
