### ISSUE TITLE
mstpr-brainbot - Deposits to EigenLayer strategy from deposit pool can revert due to `maxPerDeposit` cap in the EigenLayer strategies

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-rio-network-core-protocol-judging#5]
mstpr-brainbot

medium

# Deposits to EigenLayer strategy from deposit pool can revert due to `maxPerDeposit` cap in the EigenLayer strategies

## Summary
The collected LSTs in the deposit pool are deposited to EigenLayer when a rebalance occurs. Rio contracts only check the total cap, but they don't verify the `maxPerDeposit` in the strategy contracts of EigenLayer. If the deposit exceeds the `maxPerDeposit` set in the strategy contract, the rebalancing will revert.
## Vulnerability Detail
Best to demonstrate this with an example, so let's proceed:

Suppose there is only one operator with one strategy in the Rio network, which is the stETH strategy. Users deposit a total of 500 stETH to the contract, which is directly sent to the deposit pool, as evident in the following snippet from the coordinator contract:

```solidity
function deposit(address asset, uint256 amountIn) external checkDeposit(asset, amountIn) returns (uint256 amountOut) {
        // Convert deposited asset amount to restaking tokens.
        amountOut = convertFromAssetToRestakingTokens(asset, amountIn);

        // Pull tokens from the sender to the deposit pool.
        // @review sends directly to depositPool which the funds are stay idle till the rebalancing happens
        -> IERC20(asset).safeTransferFrom(msg.sender, address(depositPool()), amountIn);

        // Mint restaking tokens to the caller.
        token.mint(msg.sender, amountOut);

        emit Deposited(msg.sender, asset, amountIn, amountOut);
    }
```
When the rebalance is called in the coordinator, it triggers the deposit pool to deposit its balance to the EigenLayer. For the sake of this example, let's assume there are no withdrawals queued in the epoch. The following snippet will be called in the deposit pool:
```solidity
function depositBalanceIntoEigenLayer(address asset) external onlyCoordinator returns (uint256, bool) {
        .
        .
        address strategy = assetRegistry().getAssetStrategy(asset);
        uint256 sharesToAllocate = assetRegistry().convertToSharesFromAsset(asset, amountToDeposit);
        -> return (OperatorOperations.depositTokenToOperators(operatorRegistry(), asset, strategy, sharesToAllocate), isDepositCapped);
    }
```

As seen in the above snippet, the `OperatorOperations` library contract is called to deposit the stETH to operators (assuming there is only one in this example). Since there is only one operator, all the shares will be allocated to the stETH strategy, and the `stakeERC20` function will be called in the `OperatorOperations`, which does the following:

```solidity
function stakeERC20(address strategy, address token_, uint256 amount) external onlyDepositPool returns (uint256 shares) {
        if (IERC20(token_).allowance(address(this), address(strategyManager)) < amount) {
            IERC20(token_).forceApprove(address(strategyManager), type(uint256).max);
        }
        // @review deposits all the tokens to strategy
        -> shares = strategyManager.depositIntoStrategy(strategy, token_, amount);
    }
```

As observed above, all the funds are directly sent to the strategy for deposit. Inside the strategy manager contract from EigenLayer, there is a `_beforeDeposit` hook that checks the deposit amount and performs some validations:

```solidity
function _beforeDeposit(IERC20 token, uint256 amount) internal virtual override {
        require(amount <= maxPerDeposit, "StrategyBaseTVLLimits: max per deposit exceeded");
        require(_tokenBalance() <= maxTotalDeposits, "StrategyBaseTVLLimits: max deposits exceeded");

        super._beforeDeposit(token, amount);
    }
```

As seen, the deposited amount is checked to see whether it exceeds the `maxPerDeposit` allowed or not, which is not related to the total cap. In our example, if we were depositing 500 stETH and the `maxPerDeposit` is less than 500 stETH, the call will revert, making rebalancing impossible.

## Impact
Rebalance would revert. However, the owner can set the operators cap to maxPerDeposit and call rebalance quickly and then sets the cap back to normal. However, this would only solve the issue temporarily and can be frontrunned. I am not sure how to label this, will go for medium.
## Code Snippet
https://github.com/sherlock-audit/2024-02-rio-vesting-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L77-L88

https://github.com/sherlock-audit/2024-02-rio-vesting-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L121-L151

https://github.com/sherlock-audit/2024-02-rio-vesting-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/restaking/RioLRTDepositPool.sol#L47-L67

https://github.com/sherlock-audit/2024-02-rio-vesting-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/utils/OperatorOperations.sol#L51-L68

https://github.com/sherlock-audit/2024-02-rio-vesting-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/restaking/RioLRTOperatorRegistry.sol#L342-L392

https://github.com/sherlock-audit/2024-02-rio-vesting-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/restaking/RioLRTOperatorDelegator.sol#L174-L179

https://github.com/Layr-Labs/eigenlayer-contracts/blob/5c192e1a780c22e027f6861f958db90fb9ae263c/src/contracts/core/StrategyManager.sol#L323-L342

https://github.com/Layr-Labs/eigenlayer-contracts/blob/5c192e1a780c22e027f6861f958db90fb9ae263c/src/contracts/core/StrategyManager.sol#L105-L111

https://github.com/Layr-Labs/eigenlayer-contracts/blob/5c192e1a780c22e027f6861f958db90fb9ae263c/src/contracts/strategies/StrategyBaseTVLLimits.sol#L79-L84
## Tool used

Manual `Review`

## Recommendation
Check the `maxPerDeposit` in the strategy contract and cap the deposits to EigenLayer to that amount

**Comment by solimander** [comment]
Originally, we didn't want to add the gas overhead as we may not deploy ERC20 strategies until caps are removed, but I'm considering this one. Feels like it may be worth adding regardless.

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/rio-org/rio-sherlock-audit/pull/8

**Comment by zzykxx** [comment]
Escalate

This can be fixed by the admins by increasing the operator caps as described in the impact section of the report, technically valid but should be low severity.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This can be fixed by the admins by increasing the operator caps as described in the impact section of the report, technically valid but should be low severity.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
Agree with @zzykxx, I believe this is low severity, no time sensitive reverts here

**Comment by gjaldon** [comment]
@nevillehuang I'd like to point out that this issue is different from #176 because this is about `maxPerDeposit` while #176 is about `maxTotalDeposits`.

```solidity
function _beforeDeposit(IERC20 /*token*/, uint256 amount) internal virtual override {
    require(amount <= maxPerDeposit, "StrategyBaseTVLLimits: max per deposit exceeded");
    require(_tokenBalance() <= maxTotalDeposits, "StrategyBaseTVLLimits: max deposits exceeded");
}
```

The issue related to `maxTotalDeposits` in #176 can not be fixed by the admin decreasing the operator caps though. 

Rebalancing will break indefinitely until the contract is upgraded or until enough deposits are freed up in Eigenlayer so the Deposit Pool can deposit its whole balance, which seems unlikely. 

EDIT: changed increasing to decreasing for less confusion

**Comment by mstpr** [comment]
@nevillehuang
This doesn't necessarily involve "increasing" the caps, but rather decreasing them to the level allowed by `maxPerDeposit`. The admin must first decrease it to `maxPerDeposit`, then increase it back to its original value. This action isn't easy and can incur significant gas expenses for Rio admin.

For example, if `maxPerDeposit` is set at 1 ether and Rio has 100 ether to deposit, the admin must set the operator cap to 1 ether, call `rebalance`, and then revert the cap to its original value. This process will allocate 1 ether to EigenLayer, leaving 99 ether waiting in Rio. The Rio admin would need to repeat this process 99 times to fully allocate funds to EigenLayer. I believe this is a valid concern because the entire deposit flow relies on Rio's admin to perform complex and costly transactions.

However, I think in #176 the change in `maxTotalDeposits` isn't a vulnerability. If it's set lower than the amount held by Rio, Rio should simply lower its cap to match that number. This doesn't result in any loss of funds; it just means there's idle ETH in Rio that can't be allocated to EigenLayer, but users can still withdraw without any issues. On the other hand, changes to maxPerDeposit can lead to frequent errors since it pertains to partial deposits and can occur more frequently. For instance, if a rebalance fails due to exceeding maxPerDeposit, withdrawals may also become impossible.

**Comment by gjaldon** [comment]
> However, I think in https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/176 the change in maxTotalDeposits isn't a vulnerability. If it's set lower than the amount held by Rio, Rio should simply lower its cap to match that number. This doesn't result in any loss of funds; it just means there's idle ETH in Rio that can't be allocated to EigenLayer, but users can still withdraw without any issues. On the other hand, changes to maxPerDeposit can lead to frequent errors since it pertains to partial deposits and can occur more frequently. For instance, if a rebalance fails due to exceeding maxPerDeposit, withdrawals may also become impossible.

Thanks for the input. However, this statement is incorrect. The `maxTotalDeposits` check in the [Strategy](https://github.com/Layr-Labs/eigenlayer-contracts/blob/v0.2.1-goerli-m2/src/contracts/strategies/StrategyBaseTVLLimits.sol#L81) checks that the whole balance in the Strategy is within that limit.

```solidity
require(_tokenBalance() <= maxTotalDeposits, "StrategyBaseTVLLimits: max deposits exceeded");
```

Given the scenario where the token balance of the Eigenlayer Strategy is 1M and the max total deposits is at 1M, Rio lowering its cap will have no effect. Because of this, every time Rio attempts to rebalance and deposit its funds into Eigenlayer, rebalancing will revert because of the above `maxTotalDeposits` check in the Strategy. The Strategy's `maxTotalDeposits` is not checked anywhere in Rio's deposit flow.

For Rio to be able to deposit into Eigenlayer again, some other depositor should withdraw enough funds from the Eigenlayer strategy to accommodate the whole balance that is waiting to be deposited in the Rio Deposit Pool. This is highly unlikely for popular strategies and is more unlikely the larger the token balance of the Deposit Pool.

This means that tokens (LSTs) will be stuck in the Deposit Pool indefinitely and it can only be fixed with code changes. The longer the tokens are stuck in the Deposit Pool, the longer Rio has not been earning yield from Eigenlayer. However, on withdrawal, it computes the amount user can withdraw based on the [Strategy's exchange rate](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTAssetRegistry.sol#L220), which includes yield. 

```solidity
function convertToSharesFromAsset(address asset, uint256 amount) public view returns (uint256 shares) {
    shares = IStrategy(strategy).underlyingToSharesView(amount);
}
```

This means that depositors that withdraw earlier will get their principal + interest but depositors that withdraw later will not be able to withdraw either part or all of their principal.

**Comment by nevillehuang** [comment]
I believe this and issue #176 to be low severity, given caps can always be adjusted by admins as seen [here](https://github.com/Layr-Labs/eigenlayer-contracts/blob/ca5abc90d2968906690fd7cacba067022a3ff62f/src/contracts/strategies/StrategyBaseTVLLimits.sol#L46-L48). They are trusted to set appropriate limits.

**Comment by gjaldon** [comment]
Hi @nevillehuang. Those caps are in the Eigenlayer Strategy and not in Rio. Rio has no control over what caps will be set by Eigenlayer's Admins. Rio also has no control over what amounts other depositors would deposit. 

Given these reasons, I think Medium would be appropriate. I hope that makes sense.

**Comment by nevillehuang** [comment]
@gjaldon Eigen layer admins are trusted as stated in the contest details, so I believe this are acceptable risks by Rio. @solimander Am I missing something?

> Are the admins of the protocols your contracts integrate with (if any) TRUSTED or RESTRICTED?

> TRUSTED

**Comment by gjaldon** [comment]
@nevillehuang I see, but I think Trusted means that they won't act maliciously. Anyway, I don't think Eigenlayer admin can arbitrarily adjust their `maxTotalDeposits` when they want to since LST supply is limited. 

LIDO, for example, has a limit to how many stETH they can mint because they have a limited amount of validators. This means they can only stake a limited amount of ETH. I think they same limit applies to all LSTs. It's because of those limits (limited supply of LSTs because of limited amount of validators) that `maxTotalDeposits` in Eigenlayer exists and why it can not be arbitrarily adjusted.

So the case of Eigenlayer Strategies with maxed out deposits is a case that Rio needs to account for so that its rebalancing will not constantly break.

**Comment by gjaldon** [comment]
@nevillehuang I understand. But doesn't Trusted mean that they won't act maliciously? Looking at the [docs](https://docs.sherlock.xyz/audits/judging/judging#iii.-sherlocks-standards):

> When external-admin=trusted, issues related to these external admins being able to rug protocol users is not a valid issue. (Example: Aave governance has the intention of rugging Index Protocol)

In #176 there is no malicious action Eigenlayer admins need to take. Even if Eigenlayer admins are Trusted, I don't think it's reasonable to expect them to adjust config for Rio. Just sharing my thoughts ser.

**Comment by Czar102** [comment]
Using a feature of external contracts is not considered being malicious.

I don't see a reason to consider this issue to be of severity lower than Medium.

@nevillehuang should issue #176 be in a separate family?

**Comment by nevillehuang** [comment]
@Czar102 I agree, however, this issue and #176 both involves trusted external admins setting a reasonable parameter from eigen layer side. Wouldn't that be considered as rio trusting external admins? If a reasonable `maxTotalDeposit` and `maxPerDeposit` is set, the `beforeDeposit()` hook is presumed to never revert, and even it it does, it can be rectified.

**Comment by gjaldon** [comment]
@nevillehuang hope you don't mind me sharing my views on your questions. Even if `maxTotalDeposit` is a reasonable amount, that amount may be reached because Rio is not the only depositor for the Eigenlayer Strategy (there are many other depositors). Once that cap is reached, there is no guarantee if and when Eigenlayer admins will increase the `maxTotalDeposit`. The Eigenlayer admins are trusted external admins but they are not controlled by Rio, so they can not be expected to adjust configuration parameters to accommodate Rio.

> @nevillehuang should issue https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/176 be in a separate family?

@Czar102 hope you don't mind me presenting my arguments on why #176 is different from this issue. They are:
- This issue is about `maxPerDeposit` while #176 is about `maxTotalDeposits` being disregarded. The root cause identified for each issue is different.
- This issue can be fixed by Rio's admin since the Operator deposit caps can be decreased in Rio so that it is within the `maxPerDeposit`. 
- Issue #176, on the other hand, can not be fixed by Rio's admin changing configuration parameters. It's either the Eigenlayer admin increases the `maxTotalDeposits`, a sufficiently large amount of deposits are withdrawn from the Eigenlayer Strategy, or Rio makes code changes so that `DepositPool` does not break when it deposits into the Eigenlayer Strategy once it reaches the `maxTotalDeposits` cap. 
- Considering the above, the impact is different for the issues, since #176 can not be fixed by Rio's admin while this issue can be fixed by Rio's admin.

**Comment by nevillehuang** [comment]
External admins are trusted, so they are trusted to rectify/use this functions appropriately. So I stand by my previous argument to invalidate this issue and #176.

> Admin functions are assumed to be used properly, unless a list of requirements is listed and it's incomplete or if there is no scenario where a permissioned funtion can be used properly.

**Comment by Czar102** [comment]
@gjaldon isn't the `maxTotalDeposits` cap just a limitation when integrating with EigenLayer? Why does this limit exist in the first place?

Also, there seems to have been no escalation to consider issue #176 a separate one. Why is that @gjaldon?

**Comment by gjaldon** [comment]
@Czar102 my current account can't escalate yet since it's a new one.

`maxTotalDeposits` is a cap in the Eigenlayer Strategy. The issue is that Rio does not recognize this cap, so every rebalance of a strategy will attempt to deposit assets into the Strategy even when it's already maxed out. This breaks balancing and stops withdrawals from and deposits into Eigenlayer.


I asked one of the Eigenlayer devs about this and this is what they had to say:
> We’ve implemented a few mechanisms like this, ultimately all in order to prevent massive amounts of TVL flooding the system before we felt confident things were safe
> The idea was to gradually raise the caps on deposits so we could allow the TVL to increase in a controlled fashion as we grew more confident in the system

**Comment by mstpr** [comment]
> @Czar102 my current account can't escalate yet since it's a new one.
> 
> `maxTotalDeposits` is a cap in the Eigenlayer Strategy. The issue is that Rio does not recognize this cap, so every rebalance of a strategy will attempt to deposit assets into the Strategy even when it's already maxed out. This breaks balancing and stops withdrawals from and deposits into Eigenlayer.
> 
> I asked one of the Eigenlayer devs about this and this is what they had to say:
> 
> > We’ve implemented a few mechanisms like this, ultimately all in order to prevent massive amounts of TVL flooding the system before we felt confident things were safe
> > The idea was to gradually raise the caps on deposits so we could allow the TVL to increase in a controlled fashion as we grew more confident in the system

I read the comments. What would be the impact when `maxTotalDeposits` are reached in EigenLayer?

My view:
If the maxTotalDeposit in EigenLayer is reached, the Rio should also stop funds by setting its own caps. If there are idle funds regardless, then they won't be added to EigenLayer because all the caps will be filled. I don't see any vulnerability here like DoS, loss of funds etc.

"Given the scenario where the token balance of the Eigenlayer Strategy is 1M and the max total deposits is at 1M, Rio lowering its cap will have no effect."
That is not true tho? Rio can set the operators cap and prevent any further deposit, hence rebalance would work normally
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/utils/OperatorOperations.sol#L57-L59

https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/restaking/RioLRTOperatorRegistry.sol#L360

**Comment by gjaldon** [comment]
> "Given the scenario where the token balance of the Eigenlayer Strategy is 1M and the max total deposits is at 1M, Rio lowering its cap will have no effect."
> That is not true tho? Rio can set the operators cap and prevent any further deposit, hence rebalance would work normally

Hmmm, you're right. In that case, the impact for maxTotalDeposits is only temporary DOS. The Rio Admin can fix it, but since the remaining deposits to fill the cap is dynamic and dependent on other depositors, the DOS can not be fully prevented unless there are code changes. The temporary DOS blocks withdrawals of the asset and needs Rio Admin's manual intervention to fix it.

**Comment by mstpr** [comment]
> > "Given the scenario where the token balance of the Eigenlayer Strategy is 1M and the max total deposits is at 1M, Rio lowering its cap will have no effect."
> > That is not true tho? Rio can set the operators cap and prevent any further deposit, hence rebalance would work normally
> 
> Hmmm, you're right. In that case, the impact for maxTotalDeposits is only temporary DOS. The Rio Admin can fix it, but since the remaining deposits to fill the cap is dynamic and dependent on other depositors, the DOS can not be fully prevented unless there are code changes. The temporary DOS blocks withdrawals of the asset and needs Rio Admin's manual intervention to fix it.

Yes, that's why I emphasize the `maxPerDeposit` rather than `maxTotalDeposit`. If `maxTotalDeposit` is reached, then the fix is straightforward. Ideally, this value is not updated frequently. However, `maxPerDeposit` can vary widely. In such cases, admins have to execute very sophisticated transactions, which can be very expensive in terms of gas. Hence, I feel that this would be a core functionality issue because it requires significant intervention from admins.

More info on it:
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/5#issuecomment-2025509619

**Comment by Czar102** [comment]
It seems that the `maxPerDeposit` should be a rather high value, and EigenLayer should be trusted not to set it to an irrationally small value, like 1 ETH.

Based on that, I think this issue, its duplicates, including #176 and duplicates are all Low severity issues.

**Comment by Czar102** [comment]
Result:
Low
Has Duplicates

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [zzykxx](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/5/#issuecomment-2024506312): accepted

**Comment by 10xhash** [comment]
> The protocol team fixed this issue in PR/commit [rio-org/rio-sherlock-audit#8](https://github.com/rio-org/rio-sherlock-audit/pull/8).

Mitigated impact
Although deposits can still revert in the unlikely conditions (updating maxDeposit caps etc.), the impact is lowered by using a try catch block which will ensure that withdrawals can still happen

**Comment by sherlock-admin4** [comment]
The Lead Senior Watson signed off on the fix.
