### ISSUE TITLE
giraffe - Operator may undelegate themselves and cause loss or stuck funds

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-rio-network-core-protocol-judging#61]
giraffe

medium

# Operator may undelegate themselves and cause loss or stuck funds

## Summary
Operators may undelegate themselves through Eigenlayer's DelegationManager.sol which would queue a withdrawal for the staker (i.e. Rio's OperatorDelegator.sol) and allow the staker to claim after. The issue is that Rio's OperatorDelegator immediately forwards all native ETH received to the rewardsDistributor, and cannot handle withdrawals of ERC20 tokens.

## Vulnerability Detail
Operators can can 'force' undelegate themselves by calling `undelegate()` which can be called by either the staker, operator or operator's delegationApprover.
https://github.com/Layr-Labs/eigenlayer-contracts/blob/v0.2.1-goerli-m2/src/contracts/core/DelegationManager.sol#L211C5-L221C11
```solidity
function undelegate(address staker) external onlyWhenNotPaused(PAUSED_ENTER_WITHDRAWAL_QUEUE) returns (bytes32[] memory withdrawalRoots) {
        address operator = delegatedTo[staker];
        require(
            msg.sender == staker ||
                msg.sender == operator ||
                msg.sender == _operatorDetails[operator].delegationApprover,
            "DelegationManager.undelegate: caller cannot undelegate staker"
        );

		if (msg.sender != staker) {
            emit StakerForceUndelegated(staker, operator);
        }
		... 
```

This queues a withdrawal, setting the staker as withdrawer which would be Rio's OperatorDelegator contract:
```solidity
 withdrawalRoots[i] = _removeSharesAndQueueWithdrawal({
                    staker: staker,
                    operator: operator,
                    withdrawer: staker,
                    strategies: singleStrategy,
                    shares: singleShare
                });
```

After queuing, just like a regular queued withdrawer, the staker has to call `completeQueuedWithdrawal()` to receive the tokens. In Rio's setup, anyone can go to DepositPool.sol to call `completeOperatorWithdrawalForAsset` which will call OperatorDelegator to call`completeQueuedWithdrawal()` on Eigenlayer.

The problem however is that in Rio's architecture OperatorDelegator is not meant to receive ETH/tokens deposits from Eigenlayer (depositPool/withdrawQueue are the correct recipients). So, any native ETH sent to OperatorDelegator is forwarded via `receive()` to the RewardsDistributor to be distributed between the treasury, operator and depositPool. There is also no withdraw function for ERC20 tokens sent to OperatorDelegator.
## Impact
If we assume the Operator is acting maliciously (judge's guidance was that operators **aren't** trusted in the context of the in-scope contracts), then this attack could be pulled off at no cost to instantly earn 5% (`operatorETHValidatorRewardShareBPS`) of deposited ETH distributed through the RewardsDistributor. 

Even if Operators are assumed to be honest, it could also happen accidentally as operators manage many validators not just for Rio but a variety of protocols. There is a slim chance that the wrong validator could be exited and undelegated.

If it occurs, there will be a temporary DOS of funds and Rio will have to recover ETH from the operator and treasury, and/or upgrade their contracts to recover any stuck funds.
## Code Snippet
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTOperatorDelegator.sol#L244
https://github.com/Layr-Labs/eigenlayer-contracts/blob/v0.2.1-goerli-m2/src/contracts/core/DelegationManager.sol#L211

## Tool used
Manual Review
## Recommendation
1. Consider adding a pause mechanism on RewardsDistributor, which will halt the distribution of rewards when an `undelegate` event is observed.
2. Consider adding a withdrawal function to recover ERC20 tokens from OperatorDelegator.

**Comment by giraffe0x** [comment]
Escalate.

This should not be a duplicate of #53 because it points to a different root issue which requires a different fix.

For this issue #61, the remedy points towards preventing DOS by managing the distribution of rewards and adding a withdrawal function. 

For #53, the main issue is LRT exchange rate manipulation resulting in profit (high severity). #53 did not provide a recommendation but my duplicate in #184 does, which could be considered. I would also argue that #184 is the better report as it provides other reasons why LRT exchange rate manipulation could happen. 

Although both issues may be initiated due to an operator undelegating, that is something which can't be fixed as it is part of Eigenlayer.

**Comment by nevillehuang** [comment]
This issue was highlighted in scenario 1 in #53 so I believe should remain duplicates. #184 lacks a coded PoC as a form of absolute proof so disagree that it should be the better report.

**Comment by giraffe0x** [comment]
Yes it was briefing mentioned in #53 but the essence and bulk of the report is regarding the LRT exchange rate manipulation. 

My main point is that there are 2 issues here: 1) LRT exchange rate manipulation, and 2) stuck/lost funds due to no withdraw function for ERC-20 tokens. Each issue requires a different fix and so should be considered separate.

**Comment by Czar102** [comment]
@giraffe0x can you elaborate why do you think this issue was "briefly mentioned", and not reported in #53?

**Comment by nevillehuang** [comment]
@giraffe0x I believe scenario 1 mentioned in issue #53 is sufficient in describing this issue.

**Comment by giraffe0x** [comment]
@Czar102 @nevillehuang 

1) There is a factual error in scenario 1 for #53: 
53's report it states " In this case, the staker is the RIO operator delegator contract, which has no implementation to withdraw the queued withdrawal request since the withdrawer must be the "msg.sender." Therefore, the operator delegator must implement that functionality in such cases. "

This is actually incorrect. As I described in the report above, "In Rio's setup, anyone can go to DepositPool.sol to call completeOperatorWithdrawalForAsset which will call OperatorDelegator to callcompleteQueuedWithdrawal() on Eigenlayer."

2) My report describes the real issue with greater detail. Let me re-elaborate here:
The real issue happens after the OperatorDelegator receives the ETH/tokens. Here there are two paths with its own problems:
a) If ETH is received, it is forwarded to the RewardsDistributor and divided between treasury, operator and depositPool. If the operator was malicious, he would receive and steal some ETH at this point. Rio would also have to recover the ETH from treasury and re-deposit it.

b) If ERC20 tokens are received, the OperatorDelegator cannot do anything with it as there is no withdraw function, so there would be stuck/lost funds.

**Comment by Czar102** [comment]
@mstpr can you commment on the first argument?

**Comment by mstpr** [comment]
@Czar102 
"This is actually incorrect. As I described in the report above, "In Rio's setup, anyone can go to DepositPool.sol to call completeOperatorWithdrawalForAsset which will call OperatorDelegator to callcompleteQueuedWithdrawal() on Eigenlayer."

This is wrong. 
When "undelegate" the "withdrawer" address set to "staker", which is the operator delegator contract:
https://github.com/Layr-Labs/eigenlayer-contracts/blob/6de01c6c16d6df44af15f0b06809dc160eac0ebf/src/contracts/core/DelegationManager.sol#L247-L254

When anyone calls deposit pools "completeOperatorWithdrawalForAsset"  function, the delegation manager "completeQueuedWithdrawals" will be called, and the "msg.sender" will be the Deposit Pool and since the withdrawer has to be the operator delegator contract, this will revert here:
https://github.com/Layr-Labs/eigenlayer-contracts/blob/6de01c6c16d6df44af15f0b06809dc160eac0ebf/src/contracts/core/DelegationManager.sol#L566-L569

Actually your report is wrong, or I am missing something. Please provide a PoC if you think I am mistaken here.


Although the report is not correct here, the root cause which is operator calling "undelegate" is correctly identified by Watson. I am leaving to you on how to judge this

**Comment by nevillehuang** [comment]
@giraffe0x Can you provide a PoC to verify?

**Comment by giraffe0x** [comment]
@Czar102 @nevillehuang @mstpr 
Upon further review I believe I was mistaken and apologize for the trouble. 

Please invalidate this finding as I have another report which is already a duplicate of #53

**Comment by Czar102** [comment]
@giraffe0x I'll leave it a duplicate of #53 if it's a duplicate of #53. If you have another finding that's a duplicate of #53, the rewards will be the same as if I would have invalidated one of them.

@giraffe0x @nevillehuang is this invalid or a duplicate of #53?

**Comment by nevillehuang** [comment]
Based on @mstpr comments, should be invalidated

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [giraffe0x](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/61/#issuecomment-2019964165): accepted
